name: Continuous integration/deployment

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

env:
  ENVIRONMENT: dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1

      - run: npm install

      - run: npm run lint

      - run: npm run test

      - name: git config
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Leo Falco'
          git config --global user.email 'leonardo.falco@outlook.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git fetch --tags
          git checkout master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx lerna version --no-push
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sentry release
        if: github.ref == 'refs/heads/master'
        run: |
          npm install @sentry/cli -g
          VERSION=$(git describe --abbrev=0 --tags)
          sentry-cli releases new -p gql $VERSION --log-level=info
          sentry-cli releases set-commits --auto $VERSION --log-level=info
          sentry-cli releases finalize $VERSION --log-level=info
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: leofalco

      - uses: akhileshns/heroku-deploy@v3.4.6
        if: github.ref == 'refs/heads/master'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: gql-leo
          heroku_email: "leonardo.falco@outlook.com"

      - name: push tags
        if: github.ref == 'refs/heads/master'
        run: |
          git push --tags
          git push



